### PR TITLE
Fix compilation on Neon PostgreSQL 16.

### PR DESCRIPTION
**Pull request by hlinnaka**
See https://github.com/neondatabase/neon/pull/4761 for the PostgreSQL 16 work in Neon.

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]
Do we need to change anything in CI to make sure it continues to work?

**Comment by hlinnaka** [comment]
> Do we need to change anything in CI to make sure it continues to work?

The neon postgres CI will start building it, once https://github.com/neondatabase/neon/pull/4761 is merged.

**Comment by hlinnaka** [comment]
Pushed, thanks for the review!

**Comment by tristan957** [comment]
No problem. Nice catch :).

**Pull request merged**
